version: "3.8"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: job-system-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/jobs
      REDIS_HOST: redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    # ❌ REMOVED container_name (this enables scaling)
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/jobs
      REDIS_HOST: redis
    restart: always

  redis:
    image: redis:7
    container_name: job-system-redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    container_name: job-system-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
    restart: always