version: "3.8"

services:

  api:
    build: ./api
    container_name: job-system-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/jobs
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - db

  worker:
    build: ./worker
    container_name: job-system-worker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/jobs
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: job-system-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: job-system-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"